### ISSUE TITLE
bower.json incorrect main

### ISSUE THREAD

**Issue by electronicott** [a-x-/markdown-browser#1]
the wiredep plugin will not ouptut this package because
the bower.json file states `"main": "./lib/index.js"`, but it should
be `"main": "markdown.js"`

**Comment by a-x-** [comment]
Oh, thank you!

**Comment by a-x-** [comment]
all right?

**Comment by electronicott** [comment]
could you also tag the revision so bower fetches it? at the moment still the old version is checked out via `bower install`

**Comment by a-x-** [comment]
https://github.com/a-x-/markdown-browser/releases/tag/0.6.0-beta2

Good?
